<?php

namespace Database\Seeders;

use App\Models\Skpd;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SkpdTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'kode_skpd' => '101002.00000.00000',
                'nama_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 1,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '101002.11001.00000',
                'nama_skpd' => 'Sekretariat dan Bidang pada Dinas Pendidikan dan Kebudayaan',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '101002.11101.00000',
                'nama_skpd' => 'Kelompok Bermain dan Taman Kanak-Kanak Negeri Pembina Lembursitu',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '101002.11102.00000',
                'nama_skpd' => 'PAUD Situendah',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '101002.11103.00000',
                'nama_skpd' => 'TK Negeri Pembina Baros',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '101002.11104.00000',
                'nama_skpd' => 'TK Negeri Pembina Cibeureum',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '101002.11201.00000',
                'nama_skpd' => 'SD Negeri Cimanggah 1',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11202.00000',
                'nama_skpd' => 'SD Negeri Kibodas',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11203.00000',
                'nama_skpd' => 'SD Negeri Subangjaya 1',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11204.00000',
                'nama_skpd' => 'SD Negeri Sukasirna',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11205.00000',
                'nama_skpd' => 'SD Negeri Cikol',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11206.00000',
                'nama_skpd' => 'SD Negeri Cimanggah 2',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11207.00000',
                'nama_skpd' => 'SD Negeri Kabandungan',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11208.00000',
                'nama_skpd' => 'SD Negeri Pintukisi',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11209.00000',
                'nama_skpd' => 'SD Negeri Subang Jaya 3',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11210.00000',
                'nama_skpd' => 'SD Negeri Subangjaya 2',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11211.00000',
                'nama_skpd' => 'SD Negeri Cisarua',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11212.00000',
                'nama_skpd' => 'SD Negeri Dewi Sartika CBM',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11213.00000',
                'nama_skpd' => 'SD Negeri Kebonjati',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11214.00000',
                'nama_skpd' => 'SD Negeri Perana',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11215.00000',
                'nama_skpd' => 'SD Negeri Suryakencana CBM',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11216.00000',
                'nama_skpd' => 'SD Negeri Babakan Bandung',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11217.00000',
                'nama_skpd' => 'SD Negeri Babakan Caringin',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11218.00000',
                'nama_skpd' => 'SD Negeri Cijangkar 2',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11219.00000',
                'nama_skpd' => 'SD Negeri Cijangkar I',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11220.00000',
                'nama_skpd' => 'SD Negeri Cipanas',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11221.00000',
                'nama_skpd' => 'SD Negeri Cisarua 1',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11222.00000',
                'nama_skpd' => 'SD Negeri Citamiang 2',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11223.00000',
                'nama_skpd' => 'SD Negeri Citamiang I',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11224.00000',
                'nama_skpd' => 'SD Negeri Gunung Parang',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11225.00000',
                'nama_skpd' => 'SD Negeri Kebon Kawung',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11226.00000',
                'nama_skpd' => 'SD Negeri Lamping 1',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11227.00000',
                'nama_skpd' => 'SD Negeri Lamping 2',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11228.00000',
                'nama_skpd' => 'SD Negeri Lamping 3',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11229.00000',
                'nama_skpd' => 'SD Negeri Nanggeleng 1',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11230.00000',
                'nama_skpd' => 'SD Negeri Nanggeleng 2',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11231.00000',
                'nama_skpd' => 'SD Negeri Otista',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11232.00000',
                'nama_skpd' => 'SD Negeri Tonjong 2',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11233.00000',
                'nama_skpd' => 'SD Negeri Tonjong I',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11234.00000',
                'nama_skpd' => 'SD Negeri Begeg',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11235.00000',
                'nama_skpd' => 'SD Negeri Cisuda',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11236.00000',
                'nama_skpd' => 'SD Negeri Pakujajar CBM',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11237.00000',
                'nama_skpd' => 'SD Negeri Benteng 2',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11238.00000',
                'nama_skpd' => 'SD Negeri Bunut',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11239.00000',
                'nama_skpd' => 'SD Negeri Caringin Ngumbang',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11240.00000',
                'nama_skpd' => 'SD Negeri Dayeuh Luhur 4',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11241.00000',
                'nama_skpd' => 'SD Negeri Dayeuh Luhur Kulon',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11242.00000',
                'nama_skpd' => 'SD Negeri Nyomplong',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11243.00000',
                'nama_skpd' => 'SD Negeri Pajagalan',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11244.00000',
                'nama_skpd' => 'SD Negeri Sukakarya 1',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11245.00000',
                'nama_skpd' => 'SD Negeri Sukakarya Ii',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11246.00000',
                'nama_skpd' => 'SD Negeri Warudoyong',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11247.00000',
                'nama_skpd' => 'SD Negeri Babakan Sirna',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11248.00000',
                'nama_skpd' => 'SD Negeri Benteng 1',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11249.00000',
                'nama_skpd' => 'SD Negeri Benteng 3',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11250.00000',
                'nama_skpd' => 'SD Negeri Cemerlang',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11251.00000',
                'nama_skpd' => 'SD Negeri Cipanengah',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11252.00000',
                'nama_skpd' => 'SD Negeri Dayeuhluhur CBM',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11253.00000',
                'nama_skpd' => 'SD Negeri Dwikora',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11254.00000',
                'nama_skpd' => 'SD Negeri Nagrak',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11255.00000',
                'nama_skpd' => 'SD Negeri Babakan Karamat',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11256.00000',
                'nama_skpd' => 'SD Negeri Brawijaya',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11257.00000',
                'nama_skpd' => 'SD Negeri Cipelangged',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11258.00000',
                'nama_skpd' => 'SD Negeri Ciseureuh',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11259.00000',
                'nama_skpd' => 'SD Negeri Gunungpuyuh Cipta Bina Mandiri',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11260.00000',
                'nama_skpd' => 'SD Negeri Karamat Randu',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11261.00000',
                'nama_skpd' => 'SD Negeri Karang Tengah',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11262.00000',
                'nama_skpd' => 'SD Negeri Kopeng I',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11263.00000',
                'nama_skpd' => 'SD Negeri Kopeng Ii',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11264.00000',
                'nama_skpd' => 'SD Negeri Kotaparis',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11265.00000',
                'nama_skpd' => 'SD Negeri Lembursitu Ii',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11266.00000',
                'nama_skpd' => 'SD Negeri Rawasalak',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11267.00000',
                'nama_skpd' => 'SD Negeri SKIP',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11268.00000',
                'nama_skpd' => 'SD Negeri Sriwidari 1',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11269.00000',
                'nama_skpd' => 'SD Negeri Sriwidari 2',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11270.00000',
                'nama_skpd' => 'SD Negeri Tanjung Sari',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11271.00000',
                'nama_skpd' => 'SD Negeri Tegalpari',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11272.00000',
                'nama_skpd' => 'SD Negeri Cipanengah CBM',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11273.00000',
                'nama_skpd' => 'SD Negeri Lembursitu',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11274.00000',
                'nama_skpd' => 'SD Negeri Cicadas',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11275.00000',
                'nama_skpd' => 'SD Negeri Kibitay',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11276.00000',
                'nama_skpd' => 'SD Negeri Nanggerang',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11277.00000',
                'nama_skpd' => 'SD Negeri Cikundul',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11278.00000',
                'nama_skpd' => 'SD Negeri Sindangsari',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11279.00000',
                'nama_skpd' => 'SD Negeri Situ Endah',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11280.00000',
                'nama_skpd' => 'SD Negeri Situged',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11281.00000',
                'nama_skpd' => 'SD Negeri Balandongan',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11282.00000',
                'nama_skpd' => 'SD Negeri Baros 3',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11283.00000',
                'nama_skpd' => 'SD Negeri Genteng',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11284.00000',
                'nama_skpd' => 'SD Negeri Tespong Raya',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11285.00000',
                'nama_skpd' => 'SD Negeri Baros Kencana CBM',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11286.00000',
                'nama_skpd' => 'SD Negeri Cicadas Girang',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11287.00000',
                'nama_skpd' => 'SD Negeri Sudajayahilir',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11288.00000',
                'nama_skpd' => 'SD Negeri Babakan',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11289.00000',
                'nama_skpd' => 'SD Negeri Ciandam',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11290.00000',
                'nama_skpd' => 'SD Negeri Cibeureum Hilir 3',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11291.00000',
                'nama_skpd' => 'SD Negeri Cibeureum Hilir 5',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11292.00000',
                'nama_skpd' => 'SD Negeri Cibeureumhilir I',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11293.00000',
                'nama_skpd' => 'SD Negeri Cibungur',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11294.00000',
                'nama_skpd' => 'SD Negeri Limusnunggal I',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11295.00000',
                'nama_skpd' => 'SD Negeri Limusnunggal Ii',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11296.00000',
                'nama_skpd' => 'SD Negeri Loasari',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11297.00000',
                'nama_skpd' => 'SD Negeri Manunggal Bhakti',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11298.00000',
                'nama_skpd' => 'SD Negeri Pelita Jaya',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11299.00000',
                'nama_skpd' => 'SD Negeri Rancakadu',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11300.00000',
                'nama_skpd' => 'SD Negeri Selakaso',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated'
            ],
            [
                'kode_skpd' => '101002.11301.00000',
                'nama_skpd' => 'SMP Negeri 1',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '101002.11302.00000',
                'nama_skpd' => 'SMP Negeri 2',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '101002.11303.00000',
                'nama_skpd' => 'SMP Negeri 3',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '101002.11304.00000',
                'nama_skpd' => 'SMP Negeri 4',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '101002.11305.00000',
                'nama_skpd' => 'SMP Negeri 5',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '101002.11306.00000',
                'nama_skpd' => 'SMP Negeri 6',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '101002.11307.00000',
                'nama_skpd' => 'SMP Negeri 7',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '101002.11308.00000',
                'nama_skpd' => 'SMP Negeri 8',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '101002.11309.00000',
                'nama_skpd' => 'SMP Negeri 9',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '101002.11310.00000',
                'nama_skpd' => 'SMP Negeri 10',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '101002.11311.00000',
                'nama_skpd' => 'SMP Negeri 11',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '101002.11312.00000',
                'nama_skpd' => 'SMP Negeri 12',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '101002.11313.00000',
                'nama_skpd' => 'SMP Negeri 13',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '101002.11314.00000',
                'nama_skpd' => 'SMP Negeri 14',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '101002.11315.00000',
                'nama_skpd' => 'SMP Negeri 15',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '101002.11316.00000',
                'nama_skpd' => 'SMP Negeri 16',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '101002.11401.00000',
                'nama_skpd' => 'Sanggar Kegiatan Belajar (SKB) Kota Sukabumi',
                'kode_kelompok_skpd' => '101002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pendidikan dan Kebudayaan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '102001.00000.00000',
                'nama_skpd' => 'Dinas Kesehatan',
                'kode_kelompok_skpd' => '102001.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Kesehatan',
                'tingkat' => 1,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '102001.12001.00000',
                'nama_skpd' => 'Sekretariat dan Bidang pada Dinas Kesehatan',
                'kode_kelompok_skpd' => '102001.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Kesehatan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '102001.12101.00000',
                'nama_skpd' => 'RSUD Al-Mulk',
                'kode_kelompok_skpd' => '102001.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Kesehatan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '102001.12102.00000',
                'nama_skpd' => 'RSUD R. Syamsudin, S.H.',
                'kode_kelompok_skpd' => '102001.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Kesehatan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '102001.12201.00000',
                'nama_skpd' => 'UPTD Puskesmas Cipelang',
                'kode_kelompok_skpd' => '102001.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Kesehatan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '102001.12202.00000',
                'nama_skpd' => 'UPTD Puskesmas Karangtengah',
                'kode_kelompok_skpd' => '102001.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Kesehatan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '102001.12203.00000',
                'nama_skpd' => 'UPTD Puskesmas Selabatu',
                'kode_kelompok_skpd' => '102001.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Kesehatan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '102001.12204.00000',
                'nama_skpd' => 'UPTD Puskesmas Sukabumi',
                'kode_kelompok_skpd' => '102001.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Kesehatan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '102001.12205.00000',
                'nama_skpd' => 'UPTD Puskesmas Tipar',
                'kode_kelompok_skpd' => '102001.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Kesehatan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '102001.12206.00000',
                'nama_skpd' => 'UPTD Puskesmas Nanggeleng',
                'kode_kelompok_skpd' => '102001.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Kesehatan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '102001.12207.00000',
                'nama_skpd' => 'UPTD Puskesmas Gedong Panjang',
                'kode_kelompok_skpd' => '102001.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Kesehatan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '102001.12208.00000',
                'nama_skpd' => 'UPTD Puskesmas Pabuaran',
                'kode_kelompok_skpd' => '102001.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Kesehatan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '102001.12209.00000',
                'nama_skpd' => 'UPTD Puskesmas Sukakarya',
                'kode_kelompok_skpd' => '102001.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Kesehatan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '102001.12210.00000',
                'nama_skpd' => 'UPTD Puskesmas Benteng',
                'kode_kelompok_skpd' => '102001.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Kesehatan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '102001.12211.00000',
                'nama_skpd' => 'UPTD Puskesmas Baros',
                'kode_kelompok_skpd' => '102001.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Kesehatan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '102001.12212.00000',
                'nama_skpd' => 'UPTD Puskesmas Lembursitu',
                'kode_kelompok_skpd' => '102001.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Kesehatan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '102001.12213.00000',
                'nama_skpd' => 'UPTD Puskesmas Cikundul',
                'kode_kelompok_skpd' => '102001.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Kesehatan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '102001.12214.00000',
                'nama_skpd' => 'UPTD Puskesmas Cibeureum Hilir',
                'kode_kelompok_skpd' => '102001.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Kesehatan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '102001.12215.00000',
                'nama_skpd' => 'UPTD Puskesmas Limusnunggal',
                'kode_kelompok_skpd' => '102001.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Kesehatan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '102001.12301.00000',
                'nama_skpd' => 'UPTD Laboratorium Kesehatan',
                'kode_kelompok_skpd' => '102001.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Kesehatan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '102001.12302.00000',
                'nama_skpd' => 'UPTD Penunjang Kesehatan',
                'kode_kelompok_skpd' => '102001.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Kesehatan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '103001.00000.00000',
                'nama_skpd' => 'Dinas Pekerjaan Umum dan Tata Ruang',
                'kode_kelompok_skpd' => '103001.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pekerjaan Umum dan Tata Ruang',
                'tingkat' => 1,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '103001.13001.00000',
                'nama_skpd' => 'Sekretariat dan Bidang pada Dinas Pekerjaan Umum dan Tata Ruang',
                'kode_kelompok_skpd' => '103001.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pekerjaan Umum dan Tata Ruang',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '103001.13101.00000',
                'nama_skpd' => 'UPTD Pemakaman',
                'kode_kelompok_skpd' => '103001.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pekerjaan Umum dan Tata Ruang',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '103001.13102.00000',
                'nama_skpd' => 'UPTD Laboratorium dan Alat Berat',
                'kode_kelompok_skpd' => '103001.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pekerjaan Umum dan Tata Ruang',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '103001.13103.00000',
                'nama_skpd' => 'UPTD Rumah Susun Sederhana Sewa',
                'kode_kelompok_skpd' => '103001.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pekerjaan Umum dan Tata Ruang',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '103001.13104.00000',
                'nama_skpd' => 'UPTD Instalasi Pengelolaan Lumpur Tinja',
                'kode_kelompok_skpd' => '103001.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pekerjaan Umum dan Tata Ruang',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '105003.00000.00000',
                'nama_skpd' => 'Satuan Polisi Pamong Praja dan Pemadam Kebakaran',
                'kode_kelompok_skpd' => '105003.00000.00000',
                'nama_kelompok_skpd' => 'Satuan Polisi Pamong Praja dan Pemadam Kebakaran',
                'tingkat' => 1,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '105004.00000.00000',
                'nama_skpd' => 'Badan Penanggulangan Bencana Daerah',
                'kode_kelompok_skpd' => '105004.00000.00000',
                'nama_kelompok_skpd' => 'Badan Penanggulangan Bencana Daerah',
                'tingkat' => 1,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '106001.00000.00000',
                'nama_skpd' => 'Dinas Sosial',
                'kode_kelompok_skpd' => '106001.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Sosial',
                'tingkat' => 1,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '106001.16001.00000',
                'nama_skpd' => 'Sekretariat dan Bidang pada Dinas Sosial',
                'kode_kelompok_skpd' => '106001.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Sosial',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '106001.16101.00000',
                'nama_skpd' => 'UPTD Sistem Layanan Dan Rujukan Terpadu Repeh Rapih',
                'kode_kelompok_skpd' => '106001.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Sosial',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '207001.00000.00000',
                'nama_skpd' => 'Dinas Tenaga Kerja',
                'kode_kelompok_skpd' => '207001.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Tenaga Kerja',
                'tingkat' => 1,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '207001.27001.00000',
                'nama_skpd' => 'Sekretariat dan Bidang pada Dinas Tenaga Kerja',
                'kode_kelompok_skpd' => '207001.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Tenaga Kerja',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '207001.27101.00000',
                'nama_skpd' => 'UPTD Balai Latihan Kerja',
                'kode_kelompok_skpd' => '207001.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Tenaga Kerja',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '208006.00000.00000',
                'nama_skpd' => 'Dinas Pengendalian Penduduk Keluarga Berencana dan Pemberdayaan Perempuan Perlindungan Anak',
                'kode_kelompok_skpd' => '208006.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Pengendalian Penduduk Keluarga Berencana dan Pemberdayaan Perempuan Perlindungan Anak',
                'tingkat' => 1,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '209002.00000.00000',
                'nama_skpd' => 'Dinas Ketahanan Pangan, Pertanian dan Perikanan',
                'kode_kelompok_skpd' => '209002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Ketahanan Pangan, Pertanian dan Perikanan',
                'tingkat' => 1,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '209002.29001.00000',
                'nama_skpd' => 'Sekretariat dan Bidang pada Dinas Ketahanan Pangan, Pertanian dan Perikanan',
                'kode_kelompok_skpd' => '209002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Ketahanan Pangan, Pertanian dan Perikanan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '209002.29101.00000',
                'nama_skpd' => 'UPTD Agribisnis',
                'kode_kelompok_skpd' => '209002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Ketahanan Pangan, Pertanian dan Perikanan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '209002.29102.00000',
                'nama_skpd' => 'UPTD Kawasan Agroeduwisata Cikundul',
                'kode_kelompok_skpd' => '209002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Ketahanan Pangan, Pertanian dan Perikanan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '211001.00000.00000',
                'nama_skpd' => 'Dinas Lingkungan Hidup',
                'kode_kelompok_skpd' => '211001.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Lingkungan Hidup',
                'tingkat' => 1,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '211001.21101.00000',
                'nama_skpd' => 'Sekretariat dan Bidang pada Dinas Lingkungan Hidup',
                'kode_kelompok_skpd' => '211001.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Lingkungan Hidup',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '211001.21111.00000',
                'nama_skpd' => 'UPTD Pengelolaan Tempat Pemrosesan Akhir Sampah',
                'kode_kelompok_skpd' => '211001.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Lingkungan Hidup',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '212001.00000.00000',
                'nama_skpd' => 'Dinas Kependudukan dan Pencatatan Sipil',
                'kode_kelompok_skpd' => '212001.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Kependudukan dan Pencatatan Sipil',
                'tingkat' => 1,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '215001.00000.00000',
                'nama_skpd' => 'Dinas Perhubungan',
                'kode_kelompok_skpd' => '215001.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Perhubungan',
                'tingkat' => 1,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '215001.21001.00000',
                'nama_skpd' => 'Sekretariat dan Bidang pada Dinas Perhubungan',
                'kode_kelompok_skpd' => '215001.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Perhubungan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '215001.21101.00000',
                'nama_skpd' => 'UPTD Parkir',
                'kode_kelompok_skpd' => '215001.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Perhubungan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '215001.21102.00000',
                'nama_skpd' => 'UPTD Pengujian Kendaraan Bermotor',
                'kode_kelompok_skpd' => '215001.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Perhubungan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '215001.21202.00000',
                'nama_skpd' => 'UPTD Terminal',
                'kode_kelompok_skpd' => '215001.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Perhubungan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '216001.00000.00000',
                'nama_skpd' => 'Dinas Komunikasi dan Informatika',
                'kode_kelompok_skpd' => '216001.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Komunikasi dan Informatika',
                'tingkat' => 1,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '217007.00000.00000',
                'nama_skpd' => 'Dinas Koperasi, Usaha Mikro, Perindustrian, dan Perdagangan',
                'kode_kelompok_skpd' => '217007.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Koperasi, Usaha Mikro, Perindustrian, dan Perdagangan',
                'tingkat' => 1,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '217007.21701.00000',
                'nama_skpd' => 'Sekretariat dan Bidang pada Dinas Koperasi, Usaha Mikro, Perindustrian, dan Perdagangan',
                'kode_kelompok_skpd' => '217007.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Koperasi, Usaha Mikro, Perindustrian, dan Perdagangan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '217007.21711.00000',
                'nama_skpd' => 'UPTD Metrologi Legal',
                'kode_kelompok_skpd' => '217007.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Koperasi, Usaha Mikro, Perindustrian, dan Perdagangan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '217007.21721.00000',
                'nama_skpd' => 'UPTD Pasar 1',
                'kode_kelompok_skpd' => '217007.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Koperasi, Usaha Mikro, Perindustrian, dan Perdagangan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '217007.21722.00000',
                'nama_skpd' => 'UPTD Pasar 2',
                'kode_kelompok_skpd' => '217007.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Koperasi, Usaha Mikro, Perindustrian, dan Perdagangan',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '218001.00000.00000',
                'nama_skpd' => 'Dinas Penanaman Modal dan Pelayanan Terpadu Satu Pintu',
                'kode_kelompok_skpd' => '218001.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Penanaman Modal dan Pelayanan Terpadu Satu Pintu',
                'tingkat' => 1,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '219002.00000.00000',
                'nama_skpd' => 'Dinas Kepemudaan, Olahraga, dan Pariwisata',
                'kode_kelompok_skpd' => '219002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Kepemudaan, Olahraga, dan Pariwisata',
                'tingkat' => 1,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '223002.00000.00000',
                'nama_skpd' => 'Dinas Perpustakaan dan Arsip Daerah',
                'kode_kelompok_skpd' => '223002.00000.00000',
                'nama_kelompok_skpd' => 'Dinas Perpustakaan dan Arsip Daerah',
                'tingkat' => 1,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '401001.00000.00000',
                'nama_skpd' => 'Sekretariat Daerah',
                'kode_kelompok_skpd' => '401001.00000.00000',
                'nama_kelompok_skpd' => 'Sekretariat Daerah',
                'tingkat' => 1,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '401001.41101.00000',
                'nama_skpd' => 'Bagian Pemerintahan',
                'kode_kelompok_skpd' => '401001.00000.00000',
                'nama_kelompok_skpd' => 'Sekretariat Daerah',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '401001.41102.00000',
                'nama_skpd' => 'Bagian Hukum',
                'kode_kelompok_skpd' => '401001.00000.00000',
                'nama_kelompok_skpd' => 'Sekretariat Daerah',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '401001.41103.00000',
                'nama_skpd' => 'Bagian Kesejahteraan Rakyat',
                'kode_kelompok_skpd' => '401001.00000.00000',
                'nama_kelompok_skpd' => 'Sekretariat Daerah',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '401001.41201.00000',
                'nama_skpd' => 'Bagian Perekonomian',
                'kode_kelompok_skpd' => '401001.00000.00000',
                'nama_kelompok_skpd' => 'Sekretariat Daerah',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '401001.41202.00000',
                'nama_skpd' => 'Bagian Administrasi Pembangunan',
                'kode_kelompok_skpd' => '401001.00000.00000',
                'nama_kelompok_skpd' => 'Sekretariat Daerah',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '401001.41203.00000',
                'nama_skpd' => 'Bagian Pengadaan Barang dan Jasa',
                'kode_kelompok_skpd' => '401001.00000.00000',
                'nama_kelompok_skpd' => 'Sekretariat Daerah',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '401001.41301.00000',
                'nama_skpd' => 'Bagian Umum',
                'kode_kelompok_skpd' => '401001.00000.00000',
                'nama_kelompok_skpd' => 'Sekretariat Daerah',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '401001.41302.00000',
                'nama_skpd' => 'Bagian Organisasi',
                'kode_kelompok_skpd' => '401001.00000.00000',
                'nama_kelompok_skpd' => 'Sekretariat Daerah',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '401001.41303.00000',
                'nama_skpd' => 'Bagian Prorokol, Komunikasi, dan Tata Usaha Pimpinan',
                'kode_kelompok_skpd' => '401001.00000.00000',
                'nama_kelompok_skpd' => 'Sekretariat Daerah',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '402001.00000.00000',
                'nama_skpd' => 'Sekretariat Dewan Perwakilan Rakyat Daerah',
                'kode_kelompok_skpd' => '402001.00000.00000',
                'nama_kelompok_skpd' => 'Sekretariat Dewan Perwakilan Rakyat Daerah',
                'tingkat' => 1,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '501001.00000.00000',
                'nama_skpd' => 'Badan Perencanaan Pembangunan Daerah',
                'kode_kelompok_skpd' => '501001.00000.00000',
                'nama_kelompok_skpd' => 'Badan Perencanaan Pembangunan Daerah',
                'tingkat' => 1,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '502104.00000.00000',
                'nama_skpd' => 'Pengelola Barang Daerah',
                'kode_kelompok_skpd' => '502104.00000.00000',
                'nama_kelompok_skpd' => 'Pengelola Barang Daerah',
                'tingkat' => 1,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '502004.00000.00000',
                'nama_skpd' => 'Badan Pengelolaan Keuangan dan Pendapatan Daerah',
                'kode_kelompok_skpd' => '502004.00000.00000',
                'nama_kelompok_skpd' => 'Badan Pengelolaan Keuangan dan Pendapatan Daerah',
                'tingkat' => 1,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '503001.00000.00000',
                'nama_skpd' => 'Badan Kepegawaian dan Pengembangan Sumber Daya Manusia',
                'kode_kelompok_skpd' => '503001.00000.00000',
                'nama_kelompok_skpd' => 'Badan Kepegawaian dan Pengembangan Sumber Daya Manusia',
                'tingkat' => 1,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '601001.00000.00000',
                'nama_skpd' => 'Inspektorat Daerah',
                'kode_kelompok_skpd' => '601001.00000.00000',
                'nama_kelompok_skpd' => 'Inspektorat Daerah',
                'tingkat' => 1,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '701001.00000.00000',
                'nama_skpd' => 'Kecamatan Cikol',
                'kode_kelompok_skpd' => '701001.00000.00000',
                'nama_kelompok_skpd' => 'Kecamatan Cikol',
                'tingkat' => 1,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '701001.71000.00000',
                'nama_skpd' => 'Sekretariat Kecamatan Cikol',
                'kode_kelompok_skpd' => '701001.00000.00000',
                'nama_kelompok_skpd' => 'Kecamatan Cikol',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '701001.71001.00000',
                'nama_skpd' => 'Kelurahan Cikol',
                'kode_kelompok_skpd' => '701001.00000.00000',
                'nama_kelompok_skpd' => 'Kecamatan Cikol',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '701001.71002.00000',
                'nama_skpd' => 'Kelurahan Cisarua',
                'kode_kelompok_skpd' => '701001.00000.00000',
                'nama_kelompok_skpd' => 'Kecamatan Cikol',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '701001.71003.00000',
                'nama_skpd' => 'Kelurahan Gunungparang',
                'kode_kelompok_skpd' => '701001.00000.00000',
                'nama_kelompok_skpd' => 'Kecamatan Cikol',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '701001.71004.00000',
                'nama_skpd' => 'Kelurahan Kebonjati',
                'kode_kelompok_skpd' => '701001.00000.00000',
                'nama_kelompok_skpd' => 'Kecamatan Cikol',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '701001.71005.00000',
                'nama_skpd' => 'Kelurahan Selabatu',
                'kode_kelompok_skpd' => '701001.00000.00000',
                'nama_kelompok_skpd' => 'Kecamatan Cikol',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '701001.71006.00000',
                'nama_skpd' => 'Kelurahan Subangjaya',
                'kode_kelompok_skpd' => '701001.00000.00000',
                'nama_kelompok_skpd' => 'Kecamatan Cikol',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '701002.00000.00000',
                'nama_skpd' => 'Kecamatan Gunung Puyuh',
                'kode_kelompok_skpd' => '701002.00000.00000',
                'nama_kelompok_skpd' => 'Kecamatan Gunung Puyuh',
                'tingkat' => 1,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '701002.72000.00000',
                'nama_skpd' => 'Sekretariat Kecamatan Gunung Puyuh',
                'kode_kelompok_skpd' => '701002.00000.00000',
                'nama_kelompok_skpd' => 'Kecamatan Gunung Puyuh',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '701002.72001.00000',
                'nama_skpd' => 'Kelurahan Gunung Puyuh',
                'kode_kelompok_skpd' => '701002.00000.00000',
                'nama_kelompok_skpd' => 'Kecamatan Gunung Puyuh',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '701002.72002.00000',
                'nama_skpd' => 'Kelurahan Karamat',
                'kode_kelompok_skpd' => '701002.00000.00000',
                'nama_kelompok_skpd' => 'Kecamatan Gunung Puyuh',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '701002.72003.00000',
                'nama_skpd' => 'Kelurahan Karangtengah',
                'kode_kelompok_skpd' => '701002.00000.00000',
                'nama_kelompok_skpd' => 'Kecamatan Gunung Puyuh',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '701002.72004.00000',
                'nama_skpd' => 'Kelurahan Sriwidari',
                'kode_kelompok_skpd' => '701002.00000.00000',
                'nama_kelompok_skpd' => 'Kecamatan Gunung Puyuh',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '701003.00000.00000',
                'nama_skpd' => 'Kecamatan Citamiang',
                'kode_kelompok_skpd' => '701003.00000.00000',
                'nama_kelompok_skpd' => 'Kecamatan Citamiang',
                'tingkat' => 1,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '701003.73000.00000',
                'nama_skpd' => 'Sekretariat Kecamatan Citamiang',
                'kode_kelompok_skpd' => '701003.00000.00000',
                'nama_kelompok_skpd' => 'Kecamatan Citamiang',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '701003.73001.00000',
                'nama_skpd' => 'Kelurahan Cikondang',
                'kode_kelompok_skpd' => '701003.00000.00000',
                'nama_kelompok_skpd' => 'Kecamatan Citamiang',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '701003.73002.00000',
                'nama_skpd' => 'Kelurahan Citamiang',
                'kode_kelompok_skpd' => '701003.00000.00000',
                'nama_kelompok_skpd' => 'Kecamatan Citamiang',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '701003.73003.00000',
                'nama_skpd' => 'Kelurahan Gedongpanjang',
                'kode_kelompok_skpd' => '701003.00000.00000',
                'nama_kelompok_skpd' => 'Kecamatan Citamiang',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '701003.73004.00000',
                'nama_skpd' => 'Kelurahan Nanggeleng',
                'kode_kelompok_skpd' => '701003.00000.00000',
                'nama_kelompok_skpd' => 'Kecamatan Citamiang',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '701003.73005.00000',
                'nama_skpd' => 'Kelurahan Tipar',
                'kode_kelompok_skpd' => '701003.00000.00000',
                'nama_kelompok_skpd' => 'Kecamatan Citamiang',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '701004.00000.00000',
                'nama_skpd' => 'Kecamatan Warudoyong',
                'kode_kelompok_skpd' => '701004.00000.00000',
                'nama_kelompok_skpd' => 'Kecamatan Warudoyong',
                'tingkat' => 1,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '701004.74000.00000',
                'nama_skpd' => 'Sekretariat Kecamatan Warudoyong',
                'kode_kelompok_skpd' => '701004.00000.00000',
                'nama_kelompok_skpd' => 'Kecamatan Warudoyong',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '701004.74001.00000',
                'nama_skpd' => 'Kelurahan Benteng',
                'kode_kelompok_skpd' => '701004.00000.00000',
                'nama_kelompok_skpd' => 'Kecamatan Warudoyong',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '701004.74002.00000',
                'nama_skpd' => 'Kelurahan Dayeuhluhur',
                'kode_kelompok_skpd' => '701004.00000.00000',
                'nama_kelompok_skpd' => 'Kecamatan Warudoyong',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '701004.74003.00000',
                'nama_skpd' => 'Kelurahan Nyomplong',
                'kode_kelompok_skpd' => '701004.00000.00000',
                'nama_kelompok_skpd' => 'Kecamatan Warudoyong',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '701004.74004.00000',
                'nama_skpd' => 'Kelurahan Sukakarya',
                'kode_kelompok_skpd' => '701004.00000.00000',
                'nama_kelompok_skpd' => 'Kecamatan Warudoyong',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '701004.74005.00000',
                'nama_skpd' => 'Kelurahan Warudoyong',
                'kode_kelompok_skpd' => '701004.00000.00000',
                'nama_kelompok_skpd' => 'Kecamatan Warudoyong',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '701005.00000.00000',
                'nama_skpd' => 'Kecamatan Baros',
                'kode_kelompok_skpd' => '701005.00000.00000',
                'nama_kelompok_skpd' => 'Kecamatan Baros',
                'tingkat' => 1,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '701005.75000.00000',
                'nama_skpd' => 'Sekretariat Kecamatan Baros',
                'kode_kelompok_skpd' => '701005.00000.00000',
                'nama_kelompok_skpd' => 'Kecamatan Baros',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '701005.75001.00000',
                'nama_skpd' => 'Kelurahan Baros',
                'kode_kelompok_skpd' => '701005.00000.00000',
                'nama_kelompok_skpd' => 'Kecamatan Baros',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '701005.75002.00000',
                'nama_skpd' => 'Kelurahan Jayamekar',
                'kode_kelompok_skpd' => '701005.00000.00000',
                'nama_kelompok_skpd' => 'Kecamatan Baros',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '701005.75003.00000',
                'nama_skpd' => 'Kelurahan Jayaraksa',
                'kode_kelompok_skpd' => '701005.00000.00000',
                'nama_kelompok_skpd' => 'Kecamatan Baros',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '701005.75004.00000',
                'nama_skpd' => 'Kelurahan Sudajaya Hilir',
                'kode_kelompok_skpd' => '701005.00000.00000',
                'nama_kelompok_skpd' => 'Kecamatan Baros',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '701006.00000.00000',
                'nama_skpd' => 'Kecamatan Lembursitu',
                'kode_kelompok_skpd' => '701006.00000.00000',
                'nama_kelompok_skpd' => 'Kecamatan Lembursitu',
                'tingkat' => 1,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '701006.76000.00000',
                'nama_skpd' => 'Sekretariat Kecamatan Lembursitu',
                'kode_kelompok_skpd' => '701006.00000.00000',
                'nama_kelompok_skpd' => 'Kecamatan Lembursitu',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '701006.76001.00000',
                'nama_skpd' => 'Kelurahan Cikundul',
                'kode_kelompok_skpd' => '701006.00000.00000',
                'nama_kelompok_skpd' => 'Kecamatan Lembursitu',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '701006.76002.00000',
                'nama_skpd' => 'Kelurahan Cipanengah',
                'kode_kelompok_skpd' => '701006.00000.00000',
                'nama_kelompok_skpd' => 'Kecamatan Lembursitu',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '701006.76003.00000',
                'nama_skpd' => 'Kelurahan Lembursitu',
                'kode_kelompok_skpd' => '701006.00000.00000',
                'nama_kelompok_skpd' => 'Kecamatan Lembursitu',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '701006.76004.00000',
                'nama_skpd' => 'Kelurahan Sindangsari',
                'kode_kelompok_skpd' => '701006.00000.00000',
                'nama_kelompok_skpd' => 'Kecamatan Lembursitu',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '701006.76005.00000',
                'nama_skpd' => 'Kelurahan Situmekar',
                'kode_kelompok_skpd' => '701006.00000.00000',
                'nama_kelompok_skpd' => 'Kecamatan Lembursitu',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '701007.00000.00000',
                'nama_skpd' => 'Kecamatan Cibeureum',
                'kode_kelompok_skpd' => '701007.00000.00000',
                'nama_kelompok_skpd' => 'Kecamatan Cibeureum',
                'tingkat' => 1,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '701007.77000.00000',
                'nama_skpd' => 'Sekretariat Kecamatan Cibeureum',
                'kode_kelompok_skpd' => '701007.00000.00000',
                'nama_kelompok_skpd' => 'Kecamatan Cibeureum',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '701007.77001.00000',
                'nama_skpd' => 'Kelurahan Babakan',
                'kode_kelompok_skpd' => '701007.00000.00000',
                'nama_kelompok_skpd' => 'Kecamatan Cibeureum',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '701007.77002.00000',
                'nama_skpd' => 'Kelurahan Cibeureumhilir',
                'kode_kelompok_skpd' => '701007.00000.00000',
                'nama_kelompok_skpd' => 'Kecamatan Cibeureum',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '701007.77003.00000',
                'nama_skpd' => 'Kelurahan Limusnunggal',
                'kode_kelompok_skpd' => '701007.00000.00000',
                'nama_kelompok_skpd' => 'Kecamatan Cibeureum',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '701007.77004.00000',
                'nama_skpd' => 'Kelurahan Sindangpalay',
                'kode_kelompok_skpd' => '701007.00000.00000',
                'nama_kelompok_skpd' => 'Kecamatan Cibeureum',
                'tingkat' => 2,
                'nama_creator' => 'Generated',
            ],
            [
                'kode_skpd' => '801001.00000.00000',
                'nama_skpd' => 'Badan Kesatuan Bangsa dan Politik',
                'kode_kelompok_skpd' => '801001.00000.00000',
                'nama_kelompok_skpd' => 'Badan Kesatuan Bangsa dan Politik',
                'tingkat' => 1,
                'nama_creator' => 'Generated',
            ],
        ];

        try {
            foreach ($data as $key => $value) {
                $data = Skpd::firstOrCreate($value);
            }
        } catch (\Throwable $th) {
            //throw $th;
        }
    }
}
