services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    image: imc-php:latest
    container_name: imc-php
    volumes:
      - ./src/storage:/var/www/html/storage
      - ./src/bootstrap/cache:/var/www/html/bootstrap/cache
    environment:
      APP_URL: https://imcomputer.com
      DB_CONNECTION: mysql
      DB_HOST: 172.17.0.1
      DB_PORT: 3306
      DB_DATABASE: imc
      DB_USERNAME: romadlona
      DB_PASSWORD: Gromadlona1!@
      SESSION_COOKIE: imc_session
      SESSION_DOMAIN: imcomputer.com
    networks:
      - shared_net

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    image: imc-nginx:latest
    container_name: imc-nginx
    depends_on:
      - php
    networks:
      - shared_net
    labels:
      - "traefik.enable=true"

      # ROUTER (UNIK)
      - "traefik.http.routers.imc-router.rule=Host(`imcomputer.com`)"
      - "traefik.http.routers.imc-router.entrypoints=websecure"
      - "traefik.http.routers.imc-router.tls=true"
      - "traefik.http.routers.imc-router.tls.certresolver=myresolver"

      # SERVICE (UNIK & EXPLICIT)
      - "traefik.http.routers.imc-router.service=imc-nginx-svc"
      - "traefik.http.services.imc-nginx-svc.loadbalancer.server.port=80"

      - "traefik.docker.network=shared_net"

networks:
  shared_net:
    external: true
