services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    image: siadik-php:latest
    container_name: siadik-php
    restart: unless-stopped
    environment:
      # APP_ENV: production
      # APP_DEBUG: false
      APP_URL: http://36.95.57.60
      DB_CONNECTION: mysql
      DB_HOST: 172.17.0.1
      DB_PORT: 3306
      DB_DATABASE: siadik
      DB_USERNAME: siadik
      DB_PASSWORD: S14d1k!@
    networks:
      - shared_net

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    image: siadik-nginx:latest
    container_name: siadik-nginx
    restart: unless-stopped
    depends_on:
      - php
    networks:
      - shared_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.siadik.rule=Host(`36.95.57.60`)"
      - "traefik.http.routers.siadik.entrypoints=web"
      - "traefik.http.services.siadik.loadbalancer.server.port=80"
      - "traefik.docker.network=shared_net"

networks:
  shared_net:
    external: true
