<?php

namespace App\Helpers;

use Livewire\Component;
use Livewire\Livewire;

class MainHelper
{
  public $bulan = [
    1 => 'Januari',
    2 => 'Februari',
    3 => 'Maret',
    4 => 'April',
    5 => 'Mei',
    6 => 'Juni',
    7 => 'Juli',
    8 => 'Agustus',
    9 => 'September',
    10 => 'Oktober',
    11 => 'November',
    12 => 'Desember',
  ];

  public function doAlert(Component $comp, $type = "error", $message = "Terjadi Kesalahan ! <br> Silahkan Hubungi Administrator !")
  {
    $comp->dispatch('toast', type: $type, message: $message);
  }

  public $dokumenState = [
    'ls-belanja-barang-dan-jasa-kontrak' => [
      "spm" => [
        "type" => "spm",
        "title" => "SPM",
        "info" => "Format File Harus Berupa (PDF / JPG / JPEG / PNG) !",
        "rules" => "required|file|mimes:pdf,jpg,jpeg,png|max:5120",
        "uuid" => null,
        "disk" => null,
        "folder" => null,
        "filename" => null,
        "path" => null,
        "status" => 0,
        "status_label" => "-",
        "catatan_verifikator" => "-",
        "catatan_validator" => "-",
      ],
      "resume" => [
        "type" => "resume",
        "title" => "RESUME",
        "info" => "Format File Harus Berupa (PDF / JPG / JPEG / PNG) !",
        "rules" => "required|file|mimes:pdf,jpg,jpeg,png|max:5120",
        "uuid" => null,
        "disk" => null,
        "folder" => null,
        "filename" => null,
        "path" => null,
        "status" => 0,
        "status_label" => "-",
        "catatan_verifikator" => "-",
        "catatan_validator" => "-",
      ],
      "surat-tanggung-jawab-mutlak-bermaterai" => [
        "type" => "surat-tanggung-jawab-mutlak-bermaterai",
        "title" => "SURAT TANGGUNG JAWAB MUTLAK (BERMATERAI)",
        "info" => "Format File Harus Berupa (PDF / JPG / JPEG / PNG) !",
        "rules" => "required|file|mimes:pdf,jpg,jpeg,png|max:5120",
        "uuid" => null,
        "disk" => null,
        "folder" => null,
        "filename" => null,
        "path" => null,
        "status" => 0,
        "status_label" => "-",
        "catatan_verifikator" => "-",
        "catatan_validator" => "-",
      ],
      "surat-tanggung-jawab-verifikasi" => [
        "type" => "surat-tanggung-jawab-verifikasi",
        "title" => "SURAT TANGGUNG JAWAB VERIFIKASI",
        "info" => "Format File Harus Berupa (PDF / JPG / JPEG / PNG) !",
        "rules" => "required|file|mimes:pdf,jpg,jpeg,png|max:5120",
        "uuid" => null,
        "disk" => null,
        "folder" => null,
        "filename" => null,
        "path" => null,
        "status" => 0,
        "status_label" => "-",
        "catatan_verifikator" => "-",
        "catatan_validator" => "-",
      ],
      "spksp" => [
        "type" => "spksp",
        "title" => "SPK/SP",
        "info" => "Format File Harus Berupa (PDF / JPG / JPEG / PNG) !",
        "rules" => "required|file|mimes:pdf,jpg,jpeg,png|max:5120",
        "uuid" => null,
        "disk" => null,
        "folder" => null,
        "filename" => null,
        "path" => null,
        "status" => 0,
        "status_label" => "-",
        "catatan_verifikator" => "-",
        "catatan_validator" => "-",
      ],
      "kwitansi" => [
        "type" => "kwitansi",
        "title" => "KWITANSI",
        "info" => "Format File Harus Berupa (PDF / JPG / JPEG / PNG) !",
        "rules" => "required|file|mimes:pdf,jpg,jpeg,png|max:5120",
        "uuid" => null,
        "disk" => null,
        "folder" => null,
        "filename" => null,
        "path" => null,
        "status" => 0,
        "status_label" => "-",
        "catatan_verifikator" => "-",
        "catatan_validator" => "-",
      ],
      "berita-acara-selesai-pekerjaan" => [
        "type" => "berita-acara-selesai-pekerjaan",
        "title" => "BERITA ACARA SELESAI PEKERJAAN",
        "info" => "Format File Harus Berupa (PDF / JPG / JPEG / PNG) !",
        "rules" => "required|file|mimes:pdf,jpg,jpeg,png|max:5120",
        "uuid" => null,
        "disk" => null,
        "folder" => null,
        "filename" => null,
        "path" => null,
        "status" => 0,
        "status_label" => "-",
        "catatan_verifikator" => "-",
        "catatan_validator" => "-",
      ],
      "billing-pajak" => [
        "type" => "billing-pajak",
        "title" => "BILLING PAJAK",
        "info" => "Format File Harus Berupa (PDF / JPG / JPEG / PNG) !",
        "rules" => "required|file|mimes:pdf,jpg,jpeg,png|max:5120",
        "uuid" => null,
        "disk" => null,
        "folder" => null,
        "filename" => null,
        "path" => null,
        "status" => 0,
        "status_label" => "-",
        "catatan_verifikator" => "-",
        "catatan_validator" => "-",
      ],
      "bpjs-ketenagakerajaan-untuk-kontruksi-pekerjaan" => [
        "type" => "bpjs-ketenagakerajaan-untuk-kontruksi-pekerjaan",
        "title" => "BPJS KETENAGAKERAJAAN (UNTUK KONTRUKSI PEKERJAAN)",
        "info" => "Format File Harus Berupa (PDF / JPG / JPEG / PNG) !",
        "rules" => "required|file|mimes:pdf,jpg,jpeg,png|max:5120",
        "uuid" => null,
        "disk" => null,
        "folder" => null,
        "filename" => null,
        "path" => null,
        "status" => 0,
        "status_label" => "-",
        "catatan_verifikator" => "-",
        "catatan_validator" => "-",
      ],
      "foto" => [
        "type" => "foto",
        "title" => "FOTO (APABILA ADA)",
        "info" => "Format File Harus Berupa (PDF / JPG / JPEG / PNG) !",
        "rules" => "required|file|mimes:pdf,jpg,jpeg,png|max:5120",
        "uuid" => null,
        "disk" => null,
        "folder" => null,
        "filename" => null,
        "path" => null,
        "status" => 0,
        "status_label" => "-",
        "catatan_verifikator" => "-",
        "catatan_validator" => "-",
      ],
      "surat-jaminan-bank" => [
        "type" => "surat-jaminan-bank",
        "title" => "SURAT JAMINAN BANK (APABILA ADA)",
        "info" => "Format File Harus Berupa (PDF / JPG / JPEG / PNG) !",
        "rules" => "required|file|mimes:pdf,jpg,jpeg,png|max:5120",
        "uuid" => null,
        "disk" => null,
        "folder" => null,
        "filename" => null,
        "path" => null,
        "status" => 0,
        "status_label" => "-",
        "catatan_verifikator" => "-",
        "catatan_validator" => "-",
      ],
    ]
  ];
}
