<?php

namespace App\Helpers;

use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Livewire\Component;
use Livewire\Livewire;

class MainHelper
{
  public $bulan = [
    1 => 'Januari',
    2 => 'Februari',
    3 => 'Maret',
    4 => 'April',
    5 => 'Mei',
    6 => 'Juni',
    7 => 'Juli',
    8 => 'Agustus',
    9 => 'September',
    10 => 'Oktober',
    11 => 'November',
    12 => 'Desember',
  ];

  public function doAlert(Component $comp, $type = 'error', $message = 'Terjadi Kesalahan ! <br> Silahkan Hubungi Administrator !')
  {
    $comp->dispatch('toast', type: $type, message: $message);
  }

  public $dokumenState = [
    'ls-belanja-barang-dan-jasa-kontrak' => [
      'spm' => [
        'type' => 'spm',
        'title' => 'SPM',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'disk' => null,
        'folder' => null,
        'filename' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
      'resume' => [
        'type' => 'resume',
        'title' => 'RESUME',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'disk' => null,
        'folder' => null,
        'filename' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
      'surat-tanggung-jawab-mutlak-bermaterai' => [
        'type' => 'surat-tanggung-jawab-mutlak-bermaterai',
        'title' => 'SURAT TANGGUNG JAWAB MUTLAK (BERMATERAI)',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'disk' => null,
        'folder' => null,
        'filename' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
      'surat-tanggung-jawab-verifikasi' => [
        'type' => 'surat-tanggung-jawab-verifikasi',
        'title' => 'SURAT TANGGUNG JAWAB VERIFIKASI',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'disk' => null,
        'folder' => null,
        'filename' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
      'spksp' => [
        'type' => 'spksp',
        'title' => 'SPK/SP',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'disk' => null,
        'folder' => null,
        'filename' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
      'kwitansi' => [
        'type' => 'kwitansi',
        'title' => 'KWITANSI',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'disk' => null,
        'folder' => null,
        'filename' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
      'berita-acara-selesai-pekerjaan' => [
        'type' => 'berita-acara-selesai-pekerjaan',
        'title' => 'BERITA ACARA SELESAI PEKERJAAN',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'disk' => null,
        'folder' => null,
        'filename' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
      'billing-pajak' => [
        'type' => 'billing-pajak',
        'title' => 'BILLING PAJAK',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'disk' => null,
        'folder' => null,
        'filename' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
      'bpjs-ketenagakerajaan-untuk-kontruksi-pekerjaan' => [
        'type' => 'bpjs-ketenagakerajaan-untuk-kontruksi-pekerjaan',
        'title' => 'BPJS KETENAGAKERAJAAN (UNTUK KONTRUKSI PEKERJAAN)',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'disk' => null,
        'folder' => null,
        'filename' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
      'foto' => [
        'type' => 'foto',
        'title' => 'FOTO (APABILA ADA)',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'disk' => null,
        'folder' => null,
        'filename' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
      'surat-jaminan-bank' => [
        'type' => 'surat-jaminan-bank',
        'title' => 'SURAT JAMINAN BANK (APABILA ADA)',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'disk' => null,
        'folder' => null,
        'filename' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
    ],
    'ls-belanja-barang-dan-jasa-non-kontrak' => [
      'spm' => [
        'type' => 'spm',
        'title' => 'SPM',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'disk' => null,
        'folder' => null,
        'filename' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
      'resume' => [
        'type' => 'resume',
        'title' => 'RESUME',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'disk' => null,
        'folder' => null,
        'filename' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
      'surat-tanggung-jawab-mutlak-bermaterai' => [
        'type' => 'surat-tanggung-jawab-mutlak-bermaterai',
        'title' => 'SURAT TANGGUNG JAWAB MUTLAK (BERMATERAI)',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'disk' => null,
        'folder' => null,
        'filename' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
      'surat-tanggung-jawab-verifikasi' => [
        'type' => 'surat-tanggung-jawab-verifikasi',
        'title' => 'SURAT TANGGUNG JAWAB VERIFIKASI',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'disk' => null,
        'folder' => null,
        'filename' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
      'bukti-bayar-daftar-penerima' => [
        'type' => 'bukti-bayar-daftar-penerima',
        'title' => 'BUKTI BAYAR / DAFTAR PENERIMA',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'disk' => null,
        'folder' => null,
        'filename' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
      'billing-pajak' => [
        'type' => 'billing-pajak',
        'title' => 'BILLING PAJAK (APABILA ADA)',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'disk' => null,
        'folder' => null,
        'filename' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
      'foto' => [
        'type' => 'foto',
        'title' => 'FOTO (APABILA ADA)',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'disk' => null,
        'folder' => null,
        'filename' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
    ],
    'ls-hibah-dan-bansos' => [
      'surat-pernyataan-ppk-skpd' => [
        'type' => 'surat-pernyataan-ppk-skpd',
        'title' => 'Surat Pernyataan PPK SKPD',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'filename' => null,
        'disk' => null,
        'folder' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
      'proposal-awal' => [
        'type' => 'proposal-awal',
        'title' => 'Proposal awal',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'filename' => null,
        'disk' => null,
        'folder' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
      'proposal-pencairan' => [
        'type' => 'proposal-pencairan',
        'title' => 'Proposal pencairan',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'filename' => null,
        'disk' => null,
        'folder' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
      'disposisi-pimpinan' => [
        'type' => 'disposisi-pimpinan',
        'title' => 'Disposisi pimpinan',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'filename' => null,
        'disk' => null,
        'folder' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
      'surat-pernyataan-tanggung-jawab-mutlak-dari-pakpa-skpd' => [
        'type' => 'surat-pernyataan-tanggung-jawab-mutlak-dari-pakpa-skpd',
        'title' => 'Surat Pernyataan tanggung jawab mutlak dari PA/KPA SKPD',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'filename' => null,
        'disk' => null,
        'folder' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
      'photo-copy-rekening-lembaga-yang-masih-dinyatakan-aktif' => [
        'type' => 'photo-copy-rekening-lembaga-yang-masih-dinyatakan-aktif',
        'title' => 'Photo copy rekening Lembaga yang masih dinyatakan aktif',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'filename' => null,
        'disk' => null,
        'folder' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
      'photo-copy-ktp-ketua-dan-bendahara' => [
        'type' => 'photo-copy-ktp-ketua-dan-bendahara',
        'title' => 'Photo copy KTP Ketua dan Bendahara',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'filename' => null,
        'disk' => null,
        'folder' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
      'photo-copy-npwp-lembaga' => [
        'type' => 'photo-copy-npwp-lembaga',
        'title' => 'Photo copy NPWP Lembaga',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'filename' => null,
        'disk' => null,
        'folder' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
      'berit-acara-hasil-kajian-skpd' => [
        'type' => 'berit-acara-hasil-kajian-skpd',
        'title' => 'Berit acara hasil kajian SKPD',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'filename' => null,
        'disk' => null,
        'folder' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
      'legalitas-lembaga' => [
        'type' => 'legalitas-lembaga',
        'title' => 'Legalitas lembaga',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'filename' => null,
        'disk' => null,
        'folder' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
      'surat-keterangan-domisili' => [
        'type' => 'surat-keterangan-domisili',
        'title' => 'Surat keterangan domisili',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'filename' => null,
        'disk' => null,
        'folder' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
      'naskah-perjanjian-hibah-daerah' => [
        'type' => 'naskah-perjanjian-hibah-daerah',
        'title' => 'Naskah Perjanjian Hibah Daerah',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'filename' => null,
        'disk' => null,
        'folder' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ]
    ],
    'tambah-uang' => [
      'spm' => [
        'type' => 'spm',
        'title' => 'SPM',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'disk' => null,
        'folder' => null,
        'filename' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
      'resume' => [
        'type' => 'resume',
        'title' => 'RESUME',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'disk' => null,
        'folder' => null,
        'filename' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
      'surat-tanggung-jawab-mutlak-bermaterai' => [
        'type' => 'surat-tanggung-jawab-mutlak-bermaterai',
        'title' => 'SURAT TANGGUNG JAWAB MUTLAK (BERMATERAI)',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'disk' => null,
        'folder' => null,
        'filename' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
      'surat-tanggung-jawab-verifikasi' => [
        'type' => 'surat-tanggung-jawab-verifikasi',
        'title' => 'SURAT TANGGUNG JAWAB VERIFIKASI',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'disk' => null,
        'folder' => null,
        'filename' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
      'surat-pengajuan-tu' => [
        'type' => 'surat-pengajuan-tu',
        'title' => 'SURAT PENGAJUAN TU',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'disk' => null,
        'folder' => null,
        'filename' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
    ],
    'tunjangan-kinerja' => [
      'spm' => [
        'type' => 'spm',
        'title' => 'SPM',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'disk' => null,
        'folder' => null,
        'filename' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
      'resume' => [
        'type' => 'resume',
        'title' => 'RESUME',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'disk' => null,
        'folder' => null,
        'filename' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
      'surat-tanggung-jawab-mutlak-bermaterai' => [
        'type' => 'surat-tanggung-jawab-mutlak-bermaterai',
        'title' => 'SURAT TANGGUNG JAWAB MUTLAK (BERMATERAI)',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'disk' => null,
        'folder' => null,
        'filename' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
      'surat-tanggung-jawab-verifikasi' => [
        'type' => 'surat-tanggung-jawab-verifikasi',
        'title' => 'SURAT TANGGUNG JAWAB VERIFIKASI',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'disk' => null,
        'folder' => null,
        'filename' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
      'daftar-penerima-tukin' => [
        'type' => 'daftar-penerima-tukin',
        'title' => 'DAFTAR PENERIMA TUKIN (YANG SUDAH DI TANDA TANGANI)',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'disk' => null,
        'folder' => null,
        'filename' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
      'billing-pajak' => [
        'type' => 'billing-pajak',
        'title' => 'BILLING PAJAK',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'disk' => null,
        'folder' => null,
        'filename' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
      'billing-bpjs-kesehatan' => [
        'type' => 'billing-bpjs-kesehatan',
        'title' => 'BILLING BPJS KESEHATAN',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'disk' => null,
        'folder' => null,
        'filename' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
    ],
    'gaji-jkk-jkm-bpjs' => [
      'spm' => [
        'type' => 'spm',
        'title' => 'SPM',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'disk' => null,
        'folder' => null,
        'filename' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
      'resume' => [
        'type' => 'resume',
        'title' => 'RESUME',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'disk' => null,
        'folder' => null,
        'filename' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
      'surat-tanggung-jawab-mutlak-bermaterai' => [
        'type' => 'surat-tanggung-jawab-mutlak-bermaterai',
        'title' => 'SURAT TANGGUNG JAWAB MUTLAK (BERMATERAI)',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'disk' => null,
        'folder' => null,
        'filename' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
      'surat-tanggung-jawab-verifikasi' => [
        'type' => 'surat-tanggung-jawab-verifikasi',
        'title' => 'SURAT TANGGUNG JAWAB VERIFIKASI',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'disk' => null,
        'folder' => null,
        'filename' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
      'billing-pajak' => [
        'type' => 'billing-pajak',
        'title' => 'BILLING PAJAK',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'disk' => null,
        'folder' => null,
        'filename' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
      'billing-bpjs-kesehatan' => [
        'type' => 'billing-bpjs-kesehatan',
        'title' => 'BILLING BPJS KESEHATAN',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'disk' => null,
        'folder' => null,
        'filename' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
    ],
    'up-gu' => [
      'spm' => [
        'type' => 'spm',
        'title' => 'SPM',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'disk' => null,
        'folder' => null,
        'filename' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
      'resume' => [
        'type' => 'resume',
        'title' => 'RESUME',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'disk' => null,
        'folder' => null,
        'filename' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
      'surat-tanggung-jawab-mutlak-bermaterai' => [
        'type' => 'surat-tanggung-jawab-mutlak-bermaterai',
        'title' => 'SURAT TANGGUNG JAWAB MUTLAK (BERMATERAI)',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'disk' => null,
        'folder' => null,
        'filename' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
      'surat-tanggung-jawab-verifikasi' => [
        'type' => 'surat-tanggung-jawab-verifikasi',
        'title' => 'SURAT TANGGUNG JAWAB VERIFIKASI',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'disk' => null,
        'folder' => null,
        'filename' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
      'printscreen-bukti-laporan-ke-sismira-coretax' => [
        'type' => 'printscreen-bukti-laporan-ke-sismira-coretax',
        'title' => 'PRINTSCREEN BUKTI LAPORAN KE SISMIRA / CORETAX',
        'info' => 'Format File Harus Berupa (PDF / JPG / JPEG / PNG) !',
        'rules' => 'required|file|mimes:pdf,jpg,jpeg,png|max:5120',
        'uuid' => null,
        'disk' => null,
        'folder' => null,
        'filename' => null,
        'path' => null,
        'status_verifikasi' => 0,
        'status_validasi' => 0,
      ],
    ],
  ];

  public function dateFormatIndo($date)
  {
    $tanggal = date('d', strtotime($date));
    $bulan = (int) date('m', strtotime($date));
    $tahun = date('Y', strtotime($date));

    return $tanggal . ' ' . $this->bulan[$bulan] . ' ' . $tahun;
  }
}
